### ISSUE TITLE
Feature request: Coexist/integrate with Renovate

### ISSUE THREAD

**Issue by MPV** [mheap/pin-github-action#140]
I’d like to use this as a complement to Renovate which already does this, as per:
- https://docs.renovatebot.com/modules/manager/github-actions/

I.e. “just” change the comment you make from:
`# pin@0.4.0`
…into:
`# 0.4.0`

Thus I could use Renovate for:
- Upgrade to new versions
- Pin any non-pinned in master/main

And use this action for:
- Pin any non-pinned in open PRs

Would you be open to this?

Possibly configurable if changing the defaults for this breaks any consumers…?

**Comment by l0b0** [comment]
This also seems to be necessary to work with Dependabot.

**Comment by mheap** [comment]
Changing the default would require a major version bump. Please open another issue for it to be considered
