### ISSUE TITLE
`-c, --comment <string>` should parse `<string>`-formatted comments

### ISSUE THREAD

**Issue by l0b0** [mheap/pin-github-action#148]
After pinning using `--comment=' {ref}'` it's not possible to re-run the same pinning command:

```
❯ npx pin-github-action --comment=' {ref}' .github/workflows/*.y*ml
Unable to find SHA for [some action]@ v3
```

Use case: After resolving a conflict with another branch which updated an action, I might have a few actions which need to be re-pinned.

**Comment by mheap** [comment]
Thanks for the report. This is released as 1.9.1 now
