### ISSUE TITLE
Add an '--overwrite' flag to assist automation?

### ISSUE THREAD

**Issue by boldandbusted** [mheap/pin-github-action#18]
Howdy. Thank you for `pin-github-action`! :) I have the following scenario in mind in pseudocode:

* We'd like to make explicit that if:
  * there are existing commit hash, then:
    * leave hashes unchanged
  * else if:
    * there are tags (i.e. pin@v2), then:
      * convert to commit hash
* UNLESS:
  * '--overwrite' is specified as an argument to pin-github-action, then:
    * Refresh all hashes and convert all tags

This way, would could create workflows that explicitly call for updates to the hash, but other workflows will only apply pinning when a new tag-based reference is made. I hope I'm making sense. :)

**Comment by mheap** [comment]
Hey @boldandbusted!

This makes a lot of sense. I think `--update` would be a better flag rather than `--overwrite`

Would you be interested in contributing, or is this a feature request for when I find the time?

**Comment by mheap** [comment]
Actually, `--update` is the current behaviour. Maybe the new option should be `--ignore-shas` to leave things that are currently pinned as they are?

**Comment by boldandbusted** [comment]
I'm game for any name for the tag, as long as it gives the user this described ability. I think `--ignore-shas` would work, too.

Regarding contributing - I'm not against it, but I fear that my lack of experience with JS would make this quite an adventure for everyone. ;)

**Comment by mheap** [comment]
I just released #19 as v1.2.0 that has the `-i` flag for ignoring shas that are already pinned. Thanks for the request!

**Comment by boldandbusted** [comment]
Sorry for the support question - but is this version in npm yet? Thanks!

**Comment by mheap** [comment]
Yep! 

`npm update -g pin-github-action` should install it for you
