### ISSUE TITLE
Private repos require you to set process.env.GH_ADMIN_TOKEN to fetch the latest SHA

### ISSUE THREAD

**Issue by lucasgonze** [mheap/pin-github-action#73]
Hellos @mheap. Thanks for this excellent tool.

I am running it against build files in a public repo and getting an unexpected error:
```
Unable to find SHA for actions/checkout@v2
Private repos require you to set process.env.GH_ADMIN_TOKEN to fetch the latest SHA
```

These are the specific actions triggering the issue:
```
Unable to find SHA for actions/checkout@v2
Unable to find SHA for actions/github-script@v3
Unable to find SHA for actions/github-script@v3.1.0
Unable to find SHA for dorny/paths-filter@v2
Unable to find SHA for hmarr/debug-action@v2
```

My understanding is that these are not private repos and shouldn't require a token. `uses: actions/checkout@main` is an example in your own home page. 

I can work around the issue for now, but it does complicate my team's usage of the tool so it's worth asking about.

**Comment by lucasgonze** [comment]
Done. [sample.txt](https://github.com/mheap/pin-github-action/files/8673229/sample.txt) shows a complete log of one failed request matching the above pattern. I think the key is this bit:

`RequestError [HttpError]: API rate limit exceeded for 50.242.118.169. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
`

**Comment by mheap** [comment]
Yep! That'd do it. I'll add some additional handling that makes it clearer what's going on when you get rate limited.

In this case, you'll need to configure the GitHub token to increase your rate limit

**Comment by lucasgonze** [comment]
That makes total sense. I agree that a better error message would get the job done.

**Comment by mheap** [comment]
v1.6.0 just went out with a fix for the error message and better logging. Thanks for the report

**Comment by lucasgonze** [comment]
🙏 LGTM
