### ISSUE TITLE
Consider features in enclosed patch

### ISSUE THREAD

**Issue by lucasgonze** [mheap/pin-github-action#84]
For my own purposes (passing my projects yamllint configuration) I have implemented a feature to configure the yaml output formatting. To do that I upgraded the version of the yaml package to 2.x and added a little bit of code. My patches aren't polished enough for you to merge without conversation, so I'm attaching a diff rather than submitting a PR.

You would probably want new CLI parameters for custom configuration rather than hard-coding like I did here.

[patch.txt](https://github.com/mheap/pin-github-action/files/8931522/patch.txt)

**Comment by mheap** [comment]
@lucasgonze Thanks for sharing. I agree that we should allow `--yaml-line-width` and `--yaml-null-str` as CLI parameters. Apart from that this looks like a good patch

**Comment by lucasgonze** [comment]
I will implement these changes:

1. Upgrade YAML to 2.x
2. Add --yaml-line-width CLI parameter
3. Add --yaml-null-str CLI parameter
4. Bump minor version of pin-github-action

**Comment by mheap** [comment]
As this is a new feature, please bump the minor version of `pin-github-action`

**Comment by lucasgonze** [comment]
Note for future documentation: these options correspond to https://eemeli.org/yaml/#tostring-options
